package ca.matthewcarroll.geotime;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

/**
 * Supplies the Royal Caribbean app key to the web layer. Mirrors the iOS
 * ShipTimePlugin.
 *
 * The key is not in this file at all. It arrives through the generated
 * capacitor.config.json, which git does not track — see capacitor.config.ts.
 * This repository is public and the key was lifted from Royal Caribbean's own
 * client; publishing it under our name is a different act from shipping it
 * inside a binary, where it is no more exposed than in theirs.
 *
 * It has to reach native at all because only native can make the request:
 * api.rccl.com sends no CORS headers and exposes only Server-Timing, so a
 * browser can neither call it nor read environment-ship-code. A server-side
 * proxy is the answer for the web build, which cannot work aboard a ship in any
 * case — but aboard is exactly where this app must go direct.
 */
@CapacitorPlugin(name = "ShipTime")
public class ShipTimePlugin extends Plugin {

    /**
     * The key, from the plugin's own section of capacitor.config.json.
     *
     * That file is generated by `cap sync` and is not tracked by git, so the key
     * reaches the app without ever entering a committed source file and without
     * any build step rewriting one. Empty simply means a build made without the
     * secret; the web layer then hides ship features rather than offering a ship
     * whose clock can never be resolved.
     */
    private String configuredAppKey() {
        return getConfig().getString("appKey", "");
    }

    @PluginMethod
    public void appKey(PluginCall call) {
        JSObject result = new JSObject();
        result.put("key", configuredAppKey());
        call.resolve(result);
    }
}
