import UIKit
import Capacitor

// Capacitor 8 registers local plugins via a CAPBridgeViewController subclass
// (capacitor.config.json's packageClassList is regenerated by `cap sync`).
class MainViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        bridge?.registerPluginInstance(WidgetBridgePlugin())
    }
}
