import Foundation
import Capacitor

/// Supplies the Royal Caribbean app key to the web layer.
///
/// The key is not in this file at all. It arrives through the generated
/// capacitor.config.json, which git does not track — see capacitor.config.ts.
/// This repository is public and the key was lifted from Royal Caribbean's own
/// client; publishing it under our name is a different act from shipping it
/// inside a binary, where it is no more exposed than in theirs.
///
/// It has to reach native at all because only native can make the request:
/// `api.rccl.com` sends no CORS headers and exposes only `Server-Timing`, so a
/// browser can neither call it nor read `environment-ship-code`. A server-side
/// proxy is the answer for the web build, which cannot work aboard a ship in any
/// case — but aboard is exactly where this app has to go direct.
@objc(ShipTimePlugin)
public class ShipTimePlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "ShipTimePlugin"
    public let jsName = "ShipTime"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "appKey", returnType: CAPPluginReturnPromise)
    ]

    /// The key, from the plugin's own section of capacitor.config.json.
    ///
    /// That file is generated by `cap sync` and is not tracked by git, so the
    /// key reaches the app without ever entering a committed source file and
    /// without any build step rewriting one. Nil or empty simply means a build
    /// made without the secret; the web layer then hides ship features rather
    /// than offering a ship whose clock can never be resolved.
    private var configuredAppKey: String {
        bridge?.config.getPluginConfig("ShipTime").getString("appKey") ?? ""
    }

    /// Mirrors the key into the App Group so the widget can refresh without the
    /// app running. Runs once when the plugin loads.
    override public func load() {
        WidgetSharedStore.saveAppKey(configuredAppKey)
    }

    @objc func appKey(_ call: CAPPluginCall) {
        call.resolve(["key": configuredAppKey])
    }
}
